/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriagemRouteImport } from './routes/triagem'
import { Route as MinhaFilaRouteImport } from './routes/minha-fila'
import { Route as FilasEquipeRouteImport } from './routes/filas-equipe'
import { Route as IndexRouteImport } from './routes/index'

const TriagemRoute = TriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaFilaRoute = MinhaFilaRouteImport.update({
  id: '/minha-fila',
  path: '/minha-fila',
  getParentRoute: () => rootRouteImport,
} as any)
const FilasEquipeRoute = FilasEquipeRouteImport.update({
  id: '/filas-equipe',
  path: '/filas-equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/filas-equipe': typeof FilasEquipeRoute
  '/minha-fila': typeof MinhaFilaRoute
  '/triagem': typeof TriagemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/filas-equipe': typeof FilasEquipeRoute
  '/minha-fila': typeof MinhaFilaRoute
  '/triagem': typeof TriagemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/filas-equipe': typeof FilasEquipeRoute
  '/minha-fila': typeof MinhaFilaRoute
  '/triagem': typeof TriagemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/filas-equipe' | '/minha-fila' | '/triagem'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/filas-equipe' | '/minha-fila' | '/triagem'
  id: '__root__' | '/' | '/filas-equipe' | '/minha-fila' | '/triagem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilasEquipeRoute: typeof FilasEquipeRoute
  MinhaFilaRoute: typeof MinhaFilaRoute
  TriagemRoute: typeof TriagemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triagem': {
      id: '/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof TriagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-fila': {
      id: '/minha-fila'
      path: '/minha-fila'
      fullPath: '/minha-fila'
      preLoaderRoute: typeof MinhaFilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filas-equipe': {
      id: '/filas-equipe'
      path: '/filas-equipe'
      fullPath: '/filas-equipe'
      preLoaderRoute: typeof FilasEquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilasEquipeRoute: FilasEquipeRoute,
  MinhaFilaRoute: MinhaFilaRoute,
  TriagemRoute: TriagemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
