/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriagemRouteImport } from './routes/triagem'
import { Route as ScriptsRouteImport } from './routes/scripts'
import { Route as MinhaFilaRouteImport } from './routes/minha-fila'
import { Route as GestaoEntregaRouteImport } from './routes/gestao-entrega'
import { Route as FilasEquipeRouteImport } from './routes/filas-equipe'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'

const TriagemRoute = TriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsRoute = ScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaFilaRoute = MinhaFilaRouteImport.update({
  id: '/minha-fila',
  path: '/minha-fila',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoEntregaRoute = GestaoEntregaRouteImport.update({
  id: '/gestao-entrega',
  path: '/gestao-entrega',
  getParentRoute: () => rootRouteImport,
} as any)
const FilasEquipeRoute = FilasEquipeRouteImport.update({
  id: '/filas-equipe',
  path: '/filas-equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/filas-equipe': typeof FilasEquipeRoute
  '/gestao-entrega': typeof GestaoEntregaRoute
  '/minha-fila': typeof MinhaFilaRoute
  '/scripts': typeof ScriptsRoute
  '/triagem': typeof TriagemRoute
  '/clientes/$id': typeof ClientesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/filas-equipe': typeof FilasEquipeRoute
  '/gestao-entrega': typeof GestaoEntregaRoute
  '/minha-fila': typeof MinhaFilaRoute
  '/scripts': typeof ScriptsRoute
  '/triagem': typeof TriagemRoute
  '/clientes/$id': typeof ClientesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/filas-equipe': typeof FilasEquipeRoute
  '/gestao-entrega': typeof GestaoEntregaRoute
  '/minha-fila': typeof MinhaFilaRoute
  '/scripts': typeof ScriptsRoute
  '/triagem': typeof TriagemRoute
  '/clientes/$id': typeof ClientesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/filas-equipe'
    | '/gestao-entrega'
    | '/minha-fila'
    | '/scripts'
    | '/triagem'
    | '/clientes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/filas-equipe'
    | '/gestao-entrega'
    | '/minha-fila'
    | '/scripts'
    | '/triagem'
    | '/clientes/$id'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/filas-equipe'
    | '/gestao-entrega'
    | '/minha-fila'
    | '/scripts'
    | '/triagem'
    | '/clientes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FilasEquipeRoute: typeof FilasEquipeRoute
  GestaoEntregaRoute: typeof GestaoEntregaRoute
  MinhaFilaRoute: typeof MinhaFilaRoute
  ScriptsRoute: typeof ScriptsRoute
  TriagemRoute: typeof TriagemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triagem': {
      id: '/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof TriagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts': {
      id: '/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof ScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-fila': {
      id: '/minha-fila'
      path: '/minha-fila'
      fullPath: '/minha-fila'
      preLoaderRoute: typeof MinhaFilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao-entrega': {
      id: '/gestao-entrega'
      path: '/gestao-entrega'
      fullPath: '/gestao-entrega'
      preLoaderRoute: typeof GestaoEntregaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filas-equipe': {
      id: '/filas-equipe'
      path: '/filas-equipe'
      fullPath: '/filas-equipe'
      preLoaderRoute: typeof FilasEquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof ClientesRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesIdRoute: typeof ClientesIdRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesIdRoute: ClientesIdRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FilasEquipeRoute: FilasEquipeRoute,
  GestaoEntregaRoute: GestaoEntregaRoute,
  MinhaFilaRoute: MinhaFilaRoute,
  ScriptsRoute: ScriptsRoute,
  TriagemRoute: TriagemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
